# Generated by Django 6.0.5 on 2026-05-23 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('client_name', models.CharField(help_text='Name of the client making the reservation', max_length=255, verbose_name='Client Name')),
                ('table_number', models.IntegerField(help_text='Number of the table reserved', verbose_name='Table Number')),
                ('portions_reserved', models.IntegerField(help_text='Number of portions reserved for this reservation', verbose_name='Portions Reserved')),
                ('reservation_status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('prepared', 'Prepared'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created', help_text='Current status of the reservation', max_length=20, verbose_name='Reservation Status')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
