# Generated by Django 6.0.5 on 2026-06-03 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the offer', max_length=255, verbose_name='Offer Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the offer', null=True, verbose_name='Offer Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the offer', max_digits=10, verbose_name='Offer Price')),
                ('portions_available', models.IntegerField(help_text='Number of portions available for this offer', verbose_name='Portions Available')),
                ('image', models.ImageField(blank=True, help_text='Image representing the offer', null=True, upload_to='offer_images/', verbose_name='Offer Image')),
                ('category', models.CharField(choices=[('asian', 'Asian'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('american', 'American'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pizza', 'Pizza'), ('burger', 'Burger'), ('salad', 'Salad'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('kebab', 'Kebab'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('halal', 'Halal'), ('other', 'Other')], default='other', help_text='Category of the offer', max_length=20, verbose_name='Offer Category')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
